version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/multi_chain_tx_lookup/

permissions:
  - object: /var/www/multi_chain_tx_lookup/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy/start_application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/deploy/stop_application.sh
      timeout: 300
      runas: root 